### ISSUE TITLE
Would it work on 20C69?

### ISSUE THREAD

**Issue by cyrusauyeungc** [rursache/Hackintosh-i9-10900k-Z490-Vision-G#1]
first of all this build looks amazing and this is a really exciting thing to see someone made it!
I am still in the middle of picking a Ryzen or an intel 10-core due to the price. 
Just want to know if it works on 20C69 (Big Sur), and did the Airdrop/Handover/Continuity works with the T919 as long as the correct kext are used? Thanks and really appreciate your effort!

**Comment by rursache** [comment]
build advices are out of the scope of this repo
