### ISSUE TITLE
Ditch FakePCIID family

### ISSUE THREAD

**Issue by voltechs** [rursache/Hackintosh-i9-10900k-Z490-Vision-G#2]
Is there a way we can ditch the `FakePCIID.kext`? If I'm understanding this properly, it's currently only needed for the 225v injection, but that can be done via the `config.plist` through the kernel patch, right? It looks like you already have that in there, but it's disabled. When I enable it, and remove the FakePCIID kexts, it just hangs. Wondering if you have any leads on this, of if you're interested in removing it?

Great build, btw. Thanks for sharing your EFI :)

Related:
https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/issues/8
https://www.tonymacx86.com/threads/newb-sum-up-i225-v-working-on-a-gigabyte-z490-vision-g.307965/page-2
https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#deviceproperties

**Comment by sash11** [comment]
yes, I ditched fakepciid.kext in favor of device-id method in config.plist
Under your ethernet card PCI path add data field device-id that equals F3158680

<img width="561" alt="Screen Shot 2021-06-15 at 19 13 26" src="https://user-images.githubusercontent.com/16323875/122087768-c4685280-ce0d-11eb-90f0-085b5ba90fee.png">

**Comment by voltechs** [comment]
Awesome. I'll get that going. Do you plan to update to OC 0.7.0 anytime soon? Have you been able to get the new OpenCanopy (resource paths changed) working? I have not been successful at that to date 🤔 (I know, off topic haha)

**Comment by sash11** [comment]
> Awesome. I'll get that going. Do you plan to update to OC 0.7.0 anytime soon? Have you been able to get the new OpenCanopy (resource paths changed) working? I have not been successful at that to date 🤔 (I know, off topic haha)

Not sure what the author of this repo plans) For OpenCanopy you have to download new OCBinaryData, extract and replace Resources folder in your OC with the one from OCBinaryData. Then in config.plist put Acidanthera\GoldenGate value for Misc-Boot-PickerVariant.

**Comment by voltechs** [comment]
Derp! I completely overlooked that you weren't the author. My bad.

Yea I followed those steps and was not successful, but I'll give it a shot again. No doubt I'm doing something stupid. Thanks for the guidance!

**Comment by rursache** [comment]
Hey guys, sorry for the late response

I removed FakePCIID kexts because they were causing kernel panics in Monteray. However the I225-V ethernet controller no longer works. You can still use the new EFI release in 11.6.1 (Big Sur) and get it working OOB.

The new release is [here](https://github.com/rursache/Hackintosh-10900k-Z490-Vision-G-AMD-6900XT/releases/tag/v2.0)
