### ISSUE TITLE
Above 4G Decoding

### ISSUE THREAD

**Issue by xxSkyy** [rursache/Hackintosh-i9-10900k-Z490-Vision-G#3]
Your BL works great for my almost same setup but with 6800XT
but did you try booting it with enabled above 4G decoding? 
When I've got it enabled it doesn't want to boot

**Comment by rursache** [comment]
Hey, sorry for the late response.

You can update OpenCore and then enable Above 4G Decoding and Resizable Bar support in BIOS.

Also check the new EFI release as it contains support for this as well - https://github.com/rursache/Hackintosh-10900k-Z490-Vision-G-AMD-6900XT/releases/tag/v2.0
