### ISSUE TITLE
Update OpenCore?

### ISSUE THREAD

**Issue by voltechs** [rursache/Hackintosh-i9-10900k-Z490-Vision-G#4]
Hi @rursache!

Any plans to update OpenCore to the latest or maybe a 0.7.x version?

Thanks for putting this together and sharing it.

I'm using [5T33Z0's](https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore) primarily, since it's fairly updated, but I am struggling to get the front USB-C port working and saw that you had yours working.

Thanks again!

**Comment by rursache** [comment]
The repo is updated to 0.7.6 and updating to 0.8.0 is easy. just clone the opencore repo and replace the files. i update the repo only when major changes are required as incremental updates are easy and my time is limited

**Comment by voltechs** [comment]
Ah! Awesome. I was looking at the releases, but that makes sense!

**Comment by rursache** [comment]
I can understand the confusion and i'm sorry for that. However i think it's better to have releases for major updates only and repo updates for small/medium/general changes

**Comment by rursache** [comment]
updated to opencore 0.8.0 if you need help: https://github.com/rursache/Hackintosh-10900k-Z490-Vision-G-AMD-6900XT/commit/ce0fb8bc663c73d67a888c4dd527d5f1eb5c498e

**Comment by voltechs** [comment]
Thanks @rursache!

Instead of opening a new ticket, I thought I'd just piggyback here.

I put the EFI on my Big Sur thumbdrive and tried booting from it into my NVMe, but it doesn't recognize any USB when I do that. Have you experienced this or know what that might be?

**Comment by rursache** [comment]
if you don't have the exact same setup as me, this repo should be considered just guidance. if using big sur try using older commits as i'm on monteray and i don't test old OSes with each update
